### ISSUE TITLE
Date type solution proposal

### ISSUE THREAD

**Issue by NathanielJBrown97** [clayplumridge/lee-tutoring#1]
Hey there Clay,

We haven't met, but I'm also a friend of Edward. He is having me do some coding tasks for him, and I believe ultimately wants me to transfer his app scripts into your api when you're finished making the frameworks (and the front-end guy is done doing his thing). After looking through Edward's codebase I started taking a peak at what you have going on.

I'm completely new to any sort of API development, I've only used a few very rudimentary API's in the past., but I was looking into a type for dates; and apparently there used to be a maintained moment.js that was well supported, but they've since entered a maintenance mode. Perhaps, adding the luxon library for DateTime would work for your needs? From what I can tell they're regularly updated and should work well for this.

Sorry if this suggestion is out of the blue; or unwarranted. Just trying to be proactive, familiarize myself with everything, and be of some form of use.

**Comment by clayplumridge** [comment]
Hey! This was mostly thrown together in about an hour just to put some concepts down; I’m not planning to take it any further at the moment. For DateTimes, generally I’d just use UNIX timestamps on the API side; any consumer should be able to use those for whatever purpose they need, including stuff like momentjs for any manipulation or display they need to perform. That’d apply to the UX for this project as well.

**Comment by NathanielJBrown97** [comment]
Understood! I missed that key bit of information. Thanks for the advice moving forward :)
